// <auto-generated />
using MiParcialitoB.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace MiparcialitoB.Migrations
{
    [DbContext(typeof(EFCoreDbContext))]
    [Migration("20240824171746_CreateEFCoreDB1")]
    partial class CreateEFCoreDB1
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("MiparcialitoB.Models.Cursos", b =>
                {
                    b.Property<int>("CursoID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("NombreCurso")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("CursoID");

                    b.ToTable("Curso");
                });

            modelBuilder.Entity("MiparcialitoB.Models.Estudiantes", b =>
                {
                    b.Property<int>("EstudianteID")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.HasKey("EstudianteID");

                    b.ToTable("Estudiante");
                });

            modelBuilder.Entity("MiparcialitoB.Models.Inscripciones", b =>
                {
                    b.Property<int>("EstudianteID")
                        .HasColumnType("int");

                    b.Property<int>("CursoID")
                        .HasColumnType("int");

                    b.HasKey("EstudianteID", "CursoID");

                    b.HasIndex("CursoID");

                    b.ToTable("Inscripcion");
                });

            modelBuilder.Entity("MiparcialitoB.Models.Inscripciones", b =>
                {
                    b.HasOne("MiparcialitoB.Models.Cursos", "Curso")
                        .WithMany("Inscripcion")
                        .HasForeignKey("CursoID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("MiparcialitoB.Models.Estudiantes", "Estudiante")
                        .WithMany("Inscripcion")
                        .HasForeignKey("EstudianteID")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Curso");

                    b.Navigation("Estudiante");
                });

            modelBuilder.Entity("MiparcialitoB.Models.Cursos", b =>
                {
                    b.Navigation("Inscripcion");
                });

            modelBuilder.Entity("MiparcialitoB.Models.Estudiantes", b =>
                {
                    b.Navigation("Inscripcion");
                });
#pragma warning restore 612, 618
        }
    }
}
